safe: false
encoding: utf-8
markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title/
exclude: ["legacy-imports", "Rakefile", "README.md", "_template.md", "new.rb", "add-filenames-to-posts.sh"]
multivews: true

author:    "Bruno Sánchez-Andrade Nuño - brunosan"
description:    "Scientist exploring other worlds. Alien of extraordinary ability"
keywords: "science, technology, outreach, ciencia, tecnologia, divulgacion"
root_desc:      "Brunosan"


pullrequesturl : "http://prose.io/#brunosan/brunosan.eu/edit/main/"
rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants

redirects: yes
gems:
  - jekyll-redirect-from
