safe: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title/
exclude: ["legacy-imports", "Rakefile", "README.md", "_template.md", "new.rb", "add-filenames-to-posts.sh"]
multivews: true

name: Tagline
baseurl:      http://brunosan.eu
description:    "Tag line"
root_desc:      "Brunosan"

rdiscount:
    extensions: [smart]

#pullrequesturl : "https://github.com/brunosan/brunosan.eu/edit/master/_posts/"
pullrequesturl : "http://prose.io/#brunosan/brunosan.eu/edit/master/_posts/"

redirects: yes
